### ISSUE TITLE
Split scylla-artifact-tests:scylla-artifacts.py

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-artifact-tests#32]
Currently` scylla-artifact-tests:scylla-artifacts.py` contains everything, we can split ScyllaSoftwareManager, ScyllaServiceManager, Backends, ScyllaInstall, ScyllaArtifactSanity out.

Low priority.

**Comment by lmr** [comment]
Yes, but it won't be as convenient as a single file package, which was why I kept it as a single file.

**Comment by amoskong** [comment]
Close this issue.
