### ISSUE TITLE
failure_pattern in _search_scriptlet_failure

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla-artifact-tests#33]
This error ('scriptlet failure in rpm package scylla.*') comes from yum?
does it has more kind of error?
can we just check the success situation by checking the return value or using some success_patten?

```
def _search_scriptlet_failure(result):
    global SCRIPTLET_FAILURE_LIST
    output = result.stdout + result.stderr
    failure_pattern = 'scriptlet failure in rpm package scylla.*'
    if re.search(failure_pattern, output):
        pkgs = []
        occurrences = re.findall(failure_pattern, output)
        for occurrence in occurrences:
            pkg = occurrence.split()[-1]
            pkgs.append(pkg)
            SCRIPTLET_FAILURE_LIST.append(pkg)
```

**Comment by lmr** [comment]
It comes from rpm. Checking exit code won't help, the only way to know this happened is if we find that pattern in the yum install output.

**Comment by lmr** [comment]
There's no identifiable success pattern as well.
