### ISSUE TITLE
Ubuntu16: software upgrading costed about 1 hour

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla-artifact-tests#78]
[Jenkins Job](http://jenkins.cloudius-systems.com:8080/job/scylla-enterprise-2017.1-ubuntu-deb-16.04-test/label=huginn/30/console)

It costed 1 hour 28 mins, and about 1 hour was used for upgrading software before install scylla.

We uses `ReadOnly` clean vm for artifact-test, so the upgrading will waste our time in all artifact tests, until we manually update the image.

I had manually updated the ubuntu16 image, but we need a longterm solution.

Solutions:
- option 1: set an Jenkins job to upgrade and update the snapshot automatically
- option 2: write a script to upgrade and update the snapshot automatically, execute by crontab
- option 3: watch the execute time of artifact-test job, update manually (it's acceptable for me) 

@slivne @roydahan

**Comment by roydahan** [comment]
Do you think option-1 is safe enough? (won't corrupt the snapshot or something else?).
I don't mind doing option-1.

**Comment by amoskong** [comment]
We can have a backport snapshot or a independent file, it will be safe.
Current upgrade time of artifact-tests is acceptable, this task isn't urgent.

**Comment by amoskong** [comment]
@roydahan
I just found the vm (ubuntu16) used `br.archive.ubuntu.com`, not sure if it's problem of source server, I switched it to us.archive.ubuntu.com(faster).

I will keep watching the execute time of artifact-test (ubuntu 16) to know if the problem still exists.

**Comment by amoskong** [comment]
latest 2.1 artifact-tests - ubuntu16 took 19, 16, 17 mins. That's good.

Let's close this issue. I will keep watching the execute time of artifact-tests.
